apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-a
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      hostAliases:
        - ip: "100.72.47.100"
          hostnames:
            - "istiod.istio-system.svc"
            - "istiod.istio-system.svc.cluster.local"
      nodeSelector:
        node-type: edge
      containers:
        - name: ems
          image: ghcr.io/patiphan-pluem/edge-app:v5
          imagePullPolicy: IfNotPresent
          command: ["python", "ems_simulator.py"]
          env:
            - name: DB_HOST
              value: "timescaledb-service"
            - name: DB_PASS
              value: "password"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
