apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: timescaledb-external-entry
  namespace: edge-apps
spec:
  hosts:
  - timescaledb-service.edge-apps.svc.cluster.local # ชื่อที่คุณใช้ใน Code
  - timescaledb-service # ชื่อสั้น
  location: MESH_INTERNAL
  ports:
  - number: 5432
    name: tcp-postgresql
    protocol: TCP
  resolution: STATIC # บอก Envoy ว่าไม่ต้องไปถาม DNS ที่ไหน ฉันจะบอก IP ให้เอง
  endpoints:
  - address: 10.106.239.5 # ClusterIP ของ Service คุณ