apiVersion: v1
kind: Service
metadata:
  name: pmu-service
  namespace: edge-apps
spec:
  selector:
    app: pmu
  ports:
    - protocol: TCP
      port: 1410
      targetPort: 1410

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmu-deployment
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmu
  template:
    metadata:
      labels:
        app: pmu
    spec:
      nodeSelector:
        node-type: edge
      containers:
        - name: pmu
          image: ghcr.io/patiphan-pluem/edge-app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "TinyPMU.py"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 1410

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdc-deployment
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdc
  template:
    metadata:
      labels:
        app: pdc
    spec:
      nodeSelector:
        node-type: edge
      containers:
        - name: pdc
          image: ghcr.io/patiphan-pluem/edge-app:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "TinyPDC.py"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PMU_IP
              value: "pmu-service"


