# apiVersion: v1
# kind: Service
# metadata:
#   name: pmu-service
#   namespace: edge-apps
# spec:
#   clusterIP: None
#   selector:
#     app: pmu
#   ports:
#     - protocol: TCP
#       port: 1410
#       targetPort: 1410

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pmu-deployment
#   namespace: edge-apps
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pmu
#   template:
#     metadata:
#       labels:
#         app: pmu
#     spec:
#       nodeSelector:
#         node-type: edge
#       containers:
#         - name: pmu
#           image: ghcr.io/patiphan-pluem/edge-app:v3
#           imagePullPolicy: IfNotPresent
#           command: ["python", "TinyPMU.py"]
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "50m"
#             limits:
#               memory: "512Mi"
#               cpu: "500m"
#           ports:
#             - containerPort: 1410

# ---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-apps
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: pmu-service
  namespace: edge-apps
spec:
  ports:
    - protocol: TCP
      port: 1410
      targetPort: 1410
---
# 3. ระบุเลข IP ของเครื่อง PMU ที่อยู่นอก Cluster
apiVersion: v1
kind: Endpoints
metadata:
  name: pmu-service
  namespace: edge-apps
subsets:
  - addresses:
      - ip: 100.120.70.56
    ports:
      - port: 1410
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdc-deployment
  namespace: edge-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdc
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "1410"
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      labels:
        app: pdc
    spec:
      hostAliases:
        - ip: "100.72.47.100"
          hostnames:
            - "istiod.istio-system.svc"
            - "istiod.istio-system.svc.cluster.local"
      nodeSelector:
        node-type: edge
      containers:
        - name: pdc
          image: ghcr.io/patiphan-pluem/edge-app:v4
          imagePullPolicy: IfNotPresent
          command: ["python3", "TinyPDC.py"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PMU_IP
              value: "pmu-service.edge-apps.svc.cluster.local"
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: grafana
#   namespace: edge-apps
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: grafana
#   template:
#     metadata:
#       labels:
#         app: grafana
#     spec:
#       nodeSelector:
#         node-type: edge
#       securityContext:
#         fsGroup: 472
#         runAsUser: 472
#       containers:
#         - name: grafana
#           image: grafana/grafana:latest
#           ports:
#             - containerPort: 3000
#           env:
#             - name: GF_SECURITY_ADMIN_PASSWORD
#               value: "admin"
#           volumeMounts:
#             - mountPath: "/var/lib/grafana"
#               name: grafana-storage
#       volumes:
#         - name: grafana-storage
#           persistentVolumeClaim:
#             claimName: grafana-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana-service
#   namespace: edge-apps
# spec:
#   type: LoadBalancer
#   selector:
#     app: grafana
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-pvc
#   namespace: edge-apps
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 0.5Gi
