apiVersion: v1
kind: Namespace
metadata:
  name: edge-apps
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: pmu-service
  namespace: edge-apps
spec:
  ports:
    - protocol: TCP
      port: 1410
      targetPort: 1410
---
# 3. ระบุเลข IP ของเครื่อง PMU ที่อยู่นอก Cluster
apiVersion: v1
kind: Endpoints
metadata:
  name: pmu-service
  namespace: edge-apps
subsets:
  - addresses:
      - ip: 192.168.177.140
    ports:
      - port: 1410
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pdc-deployment
  namespace: edge-apps
spec:
  selector:
    matchLabels:
      app: pdc
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "1410"
      labels:
        app: pdc
    spec:
      nodeSelector:
        node-type: edge

      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet # เพื่อให้ยังคุยกับ Database ผ่าน DNS ของ K8s ได้
      containers:
        - name: pdc
          image: ghcr.io/patiphan-pluem/edge-app:v8
          imagePullPolicy: IfNotPresent
          command: ["python3", "TinyPDC.py"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PMU_IP
              value: "192.168.177.140"
            - name: DB_HOST
              value: "timescaledb-service.edge-apps"
---

